# Generated by Django 4.2.2 on 2023-08-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('m_year', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
            ],
        ),
    ]
